### ISSUE TITLE
WARNIG/INFO: ssl VERIFYHOST/VERIFYPEER is disabled

### ISSUE THREAD

**Issue by daniel100097** [paysafecard/paysafecard-rest_api-php#13]
**The currently used behavior is unsafe.**

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

https://github.com/paysafecard/paysafecard-rest_api-php/blob/21e9695016b5acae21eb3fb385fbe2080aae3aaf/payment/PaymentClass.php#L54
https://github.com/paysafecard/paysafecard-rest_api-php/blob/21e9695016b5acae21eb3fb385fbe2080aae3aaf/payment/PaymentClass.php#L55

**Comment by psc-walch** [comment]
Thanks Daniel for your review and contribution. We will check your request internally and come back on this.

**Comment by danadePSC** [comment]
Fixed.
