### ISSUE TITLE
"Capture payment" has failed. Please try again!

### ISSUE THREAD

**Issue by kuamquat940** [paysafecard/paysafecard-rest_api-php#19]
The module has a problem and does not work with the paysafecard partner integration tester.
Error: **"The debit has not been closed with "close" flag set to "1"."**
P.S: is REST API, not CLASSIC API. I documented myself and understood that the function must be executed: "executeDebit", but for REST API not exists

**Comment by AlexisSerneels** [comment]
+1

**Comment by psc-fatos** [comment]
Thank you for reporting the issue. We are investigating it internally and will provide information as soon as possible

**Comment by psc-fatos** [comment]
The issue is fixed with the latest release we had. Thank you for reporting it!
